# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-16 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Woman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('major', models.CharField(max_length=55)),
                ('response1', models.TextField()),
                ('response2', models.TextField()),
                ('response3', models.TextField()),
                ('response4', models.TextField()),
                ('response5', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
